spring.application.name=chalettaperformancedb

spring.datasource.url=jdbc:mysql://localhost:3306/chalettaperformancedb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=mysupersecretkeythatisatleast32charslong
jwt.expiration=86400000
spring.mvc.dispatch-options-request=true


app.cors.allowed-origins=http://localhost:5173

app.default-user.username=admin
app.default-user.password=admin123
app.default-user.role=ROLE_ADMIN

app.scheduler.interval-ms=15000
app.scheduler.enabled=true

app.rgc.api-url=https://ladder.rankedgaming.com/views/g4/ajax-games.php
app.rgc.room=107
app.rgc.step=30